### ISSUE TITLE
possibility to plot more than 5 ellipses 

### ISSUE THREAD

**Issue by ieiedm** [cran/eulerr#1]
Hi,

I have checked the function `venn.R` and I have seen that you can have maximum 5 ellipses. 
However, is there a way around it? I can't do it with the function `fit` because my input is not numeric but a list of lists with a number of objects inside and in total i have six input variables. 

Thanks a lot!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by ieiedm** [comment]
Thanks!
